// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goxazlfyiiomsijicorj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveGF6bGZ5aWlvbXNpamljb3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Njc2OTIsImV4cCI6MjA1OTI0MzY5Mn0.ZKMJlwuKHbZXLLJXqY2pAjDPhOw8fz1H76gEZZA4Zc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);